# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56c9a909d3fb8608ed6c686332792e2c5e9df1909aa156cfab4633fa5f7cfa5764e5ec9a8d81726b3935d087160dd7ac4e16e33518a466fd6013d7b9d6eec81e

test:
  secret_key_base: ed59d478b95fe09eb9565bff6ef2b97b0d71511f9b9b505ffb2e184c68a786092638a8b79d55a150d3d255e69cd58726c1f3f3457258e58259b927353cff2f78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
